CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20) DEFAULT 'USER' NOT NULL
);


CREATE TABLE addresses
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street  VARCHAR(255) NOT NULL,
    city    VARCHAR(255) NOT NULL,
    state   VARCHAR(255) NOT NULL,
    zip     VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_addresses_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE INDEX idx_addresses_user_id ON addresses (user_id);

CREATE TABLE categories
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)   NOT NULL,
    price       DECIMAL(10, 2) NOT NULL,
    description VARCHAR(255)           NOT NULL,
    category_id SMALLINT NULL,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE NO ACTION
);

CREATE INDEX idx_products_category_id ON products (category_id);

CREATE TABLE profiles
(
    id             BIGINT PRIMARY KEY,
    bio            VARCHAR(255) NULL,
    phone_number   VARCHAR(15) NULL,
    dob  DATE NULL,
    loyalty_points INT DEFAULT 0 NULL,
    CONSTRAINT fk_profiles_user FOREIGN KEY (id) REFERENCES users (id) ON DELETE NO ACTION
);
